export const REPORTS_TABLE_COLUMNS = [
    {
        title: "S.No",
        dataIndex: "sNo",
        key: "sNo",
        width: 80,
        align: "center",
    },
    {
        title: "CR Date",
        dataIndex: "crDate",
        key: "crDate",
        width: 140,
        align: "center",
    },
    {
        title: "Dispatch Date",
        dataIndex: "dispatchDate",
        key: "dispatchDate",
        width: 150,
        align: "center",
    },
    {
        title: "Kanban Date",
        dataIndex: "kanbanDate",
        key: "kanbanDate",
        width: 150,
        align: "center",
    },
    {
        title: "Contract No",
        dataIndex: "contractNo",
        key: "contractNo",
        width: 180,
        align: "center",
    },
    {
        title: "Part Number",
        dataIndex: "partNumber",
        key: "partNumber",
        width: 220,
        align: "center",
    },
    {
        title: "Week No",
        dataIndex: "weekNo",
        key: "weekNo",
        width: 120,
        align: "center",
    },
    {
        title: "BOM Qty",
        dataIndex: "bomQty",
        key: "bomQty",
        width: 100,
        align: "center",
    },
    {
        title: "Total Qty",
        dataIndex: "totalQty",
        key: "totalQty",
        width: 100,
        align: "center",
    },
    {
        title: "Description",
        dataIndex: "description",
        key: "description",
        width: 300,
    },
];

export const dataSource = [
    {
        key: "1",
        sNo: 1,
        crDate: "29-04-2026",
        dispatchDate: "29-04-2026",
        kanbanDate: "29-04-2026",
        contractNo: "CR-3456",
        partNumber: "RFIM1I.0-52IS5374",
        weekNo: "202638A",
        bomQty: 1,
        totalQty: 1,
        description: "False Ceiling",

        children: [
            {
                key: "1-1",
                sNo: "1.1",
                crDate: "29-04-2026",
                dispatchDate: "29-04-2026",
                kanbanDate: "29-04-2026",
                contractNo: "CR-3456-A",
                partNumber: "RFIM1I.0-52IS5374-A",
                weekNo: "202638A",
                bomQty: 2,
                totalQty: 2,
                description: "False Ceiling Child Row 1",
            },
            {
                key: "1-2",
                sNo: "1.2",
                crDate: "30-04-2026",
                dispatchDate: "30-04-2026",
                kanbanDate: "30-04-2026",
                contractNo: "CR-3456-B",
                partNumber: "RFIM1I.0-52IS5374-B",
                weekNo: "202638B",
                bomQty: 3,
                totalQty: 3,
                description: "False Ceiling Child Row 2",
            },
        ],
    },
    {
        key: "2",
        sNo: 2,
        crDate: "01-05-2026",
        dispatchDate: "30-04-2026",
        kanbanDate: "30-04-2026",
        contractNo: "CR-3465",
        partNumber: "RFIM2.0-52IS5347",
        weekNo: "202638A",
        bomQty: 1,
        totalQty: 1,
        description: "PACKAGING–11.0FM",

        children: [
            {
                key: "2-1",
                sNo: "2.1",
                crDate: "01-05-2026",
                dispatchDate: "01-05-2026",
                kanbanDate: "01-05-2026",
                contractNo: "CR-3465-A",
                partNumber: "RFIM2.0-52IS5347-A",
                weekNo: "202638A",
                bomQty: 5,
                totalQty: 5,
                description: "Packaging Child",
            },
        ],
    },
    {
        key: "3",
        sNo: 3,
        crDate: "30-04-2026",
        dispatchDate: "02-05-2026",
        kanbanDate: "01-05-2026",
        contractNo: "CR-2345",
        partNumber: "RFIM1I.0-52IS5374",
        weekNo: "202638A",
        bomQty: 1,
        totalQty: 1,
        description: "PACKAGING–GREEN CONTRACT",
    },
];
