import { audit_print_icon, disatch_icon } from "../../../assets/images";

export const AUDIT_TABLE_COLUMN = ({ handlePrintAudit, handleDispatch }) => [
    {
        title: "S.No",
        dataIndex: "sNo",
        key: "sNo",
        width: 70,
    },
    {
        title: "Part Number",
        dataIndex: "partNumber",
        key: "partNumber",
    },
    {
        title: "Week No",
        dataIndex: "weekNo",
        key: "weekNo",
    },
    {
        title: "Qty",
        dataIndex: "qty",
        key: "qty",
        width: 80,
    },
    {
        title: "Description",
        dataIndex: "description",
        key: "description",
    },
    {
        title: "Audit",
        dataIndex: "audit",
        key: "audit",
        render: (_, auditRecord) => auditRecord?.isParent ? <img style={{ cursor: "pointer" }} src={audit_print_icon} onClick={() => handlePrintAudit(auditRecord)} alt="" /> : "-",
    },
    {
        title: "Date",
        dataIndex: "date",
        key: "date",
    },
    {
        title: "Dispatch",
        dataIndex: "dispatch",
        key: "dispatch",
        render: (_, dispatchRecord) => dispatchRecord?.isParent ? <img style={{ cursor: "pointer" }} onClick={() => handleDispatch(dispatchRecord)} src={disatch_icon} alt="" /> : "-",
    },
    {
        title: "Kanban date",
        dataIndex: "kanbanDate",
        key: "kanbanDate",
    },
    {
        title: "BOM Qty",
        dataIndex: "bomQty",
        key: "bomQty",
    },
];

export const dataSource = [
    {
        key: 1,
        sNo: 1,
        partNumber: "52NIK373-LMFIM4.4",
        weekNo: "202538A",
        qty: 1,
        description: "Platform & Accessories",
        date: "29-04-2026",
        kanbanDate: "05-05-2026",
        bomQty: "",
        isParent: true,
    },
    {
        key: 2,
        sNo: 2,
        partNumber: "NAA5709AF4",
        weekNo: "202538A",
        qty: 1,
        description: "Kit for Panel/Fascia & Platform Sundries",
        audit: "",
        date: "",
        dispatch: "",
        kanbanDate: "",
        bomQty: "",
        isParent: false,
    },
    {
        key: 3,
        sNo: 3,
        partNumber: "NAA281Q2",
        weekNo: "202538A",
        qty: 1,
        description: "TOE GUARD, CLD",
        audit: "",
        date: "",
        dispatch: "",
        kanbanDate: "",
        bomQty: "",
        isParent: false,
    },
    {
        key: 4,
        sNo: 4,
        partNumber: "NAA27076C3",
        weekNo: "202538A",
        qty: 10,
        description: "KIT FOR T.C MOUNTING",
        audit: "",
        date: "",
        dispatch: "",
        kanbanDate: "",
        bomQty: "",
        isParent: false,
    },
    {
        key: 5,
        sNo: 5,
        partNumber: "NAA24240GE51",
        weekNo: "202538A",
        qty: 1,
        description: "ASSY PLATFORM-10D",
        audit: "",
        date: "",
        dispatch: "",
        kanbanDate: "",
        bomQty: "",
        isParent: false,
    },
];